### ISSUE TITLE
Make UI for the assembly module

### ISSUE THREAD

**Issue by Kif11** [Kif11/lanoria-assembly#17]

**Comment by Kif11** [comment]
Hey @YasinH I made a first pass of the UI. What do you think?
![screen shot 2016-03-04 at 10 10 53 pm](https://cloud.githubusercontent.com/assets/8003487/13546057/42a4ce5c-e256-11e5-9347-f164a9a7e848.png)

**Comment by Kif11** [comment]
You should be able to run it like that:
```python
from assembly import main
main.run()
```

**Comment by YasinH** [comment]
That's looking hot! I'll give that a go.
Looking at it, we also need to try and re-order the check boxes according to the wiki and their order of execution. For example, export cache, definitely needs to happen after pre-roll.
For now, does it only consider 50 frame pre-roll?

**Comment by Kif11** [comment]
I'm thinking should we use the same range sliders for pre-roll or separate one.

**Comment by YasinH** [comment]
OK, here's my suggestion

![assembly_ui_01](https://cloud.githubusercontent.com/assets/17615272/13547544/f717f3be-e2ec-11e5-9a65-5b99586826e9.jpg)

Couple of notes:

- Splitted into two tabs, Update tab to be used for assembling the light file after getting data from sim dept
- swap_asset_with_caches to be put under Update tab. 
- Added more space to the UI so that adding input arguments would be easier
- Not sure if we should put the Save function there or not. But if we are putting, it should only work if the scene opened is anim, not light. Otherwise the user may accidentally run it which can screw up the light file!

**Comment by Kif11** [comment]
@YasinH Here is the assembly updated UI according to your layout.
![screen shot 2016-03-05 at 10 57 51 pm](https://cloud.githubusercontent.com/assets/8003487/13552810/e561a974-e325-11e5-8247-474210eca95b.png)
I also adde it under Assembly menu as Assembly Tools.
![screen shot 2016-03-05 at 10 57 39 pm](https://cloud.githubusercontent.com/assets/8003487/13552814/f9dbba3e-e325-11e5-8894-c9e7052bab32.png)
I kept two main tabs on top. The rest is as you designed.

**Comment by YasinH** [comment]
Ah, this looks amazing, Kirill!
Perhaps the other tab to deal with updating the Light file we should add later beside the A2L tab? Not sure what to call it though because A2L is covering the whole aspects of it. 

A few minor notes:
- Could we decrease the length of the UI a bit? :) Somewhere between yours and mine. I think the sections are a bit too far from each other
- For pre-roll range it's better to keep it as a dropdown list to avoid user fault so that it fully mimics the Setup Pre-roll UI
- I think having a single frame range should totally suffice for all the Export Camera, Setup Pre-roll and Export cache. All the exports could start at the beginning at the animation timeline. I don't foresee any particular case the ranges need to be separate.

Great job!

**Comment by Kif11** [comment]
* This is  docked to the left of main maya window that why it look far apart
* This was easier to set up for now since each of the checks derived from the same widget
* Export camera start at 0 wearers export cache starts at preroll time

Also, it should be something to select which characters to export or we should decide it programmatically.

**Comment by YasinH** [comment]
- Fair enough! Let's keep it this way then. Any idea where we would add rest of the updating functions? 
- I see, let's do it whenever you feel comfortable doing it then
- Export Cache needs to start at pre-roll only for the Boy. And this is something that can be hard-coded. For example, if the anim starts at 1 then the camera, caches and pre-roll should also starts at . Pre-roll already steps back 1 frame internally to do the job so that it sets the keys at 0, 25 and 50. For special cases later such as the drools, we can figure them out on a shot basis. So yeah, let's share one range for them all.
- Let's do it programmatically so that it exports all the caches. The user can always use the dedicated cache manager if he/she wants to export caches selectively

**Comment by YasinH** [comment]
Fixed a few typos in the above comment

**Comment by Kif11** [comment]
@YasinH publish an updated UI. Please take a look.
![Uploading Screen Shot 2016-03-07 at 2.12.45 AM.png…]()

**Comment by Kif11** [comment]
Regarding to your previous question. Yes, *Run Selected* execute the functions in their display order.

**Comment by YasinH** [comment]
This looks awesome! The toggle selection is gonna come in handy!
Two last notes! 
1_ Instead of export start and export end, I'd suggest changing it to the common start frame and end frame. That's easier to understand at first glance. Or, we can just call them Start and End, this would allow the UI to get more compact horizontally and get closer to what you had before without too much empty space in the mid of UI (this issue was also present in my suggested UI). 
2_ Correct me if I'm wrong, but I guess in the previous update, the start and end frames were automatically getting fetched from the scene timeline. Can we bring it back?

**Comment by YasinH** [comment]
One more thing. Let's call the tool "Scene Assembly" in LaCaja menu

**Comment by Kif11** [comment]
I will try to make it compact if I can find the solution fast otherwise I will leave it for latter. For now we have other issues to close. I will bring the frame range back from scene timeline and rename the labels.

**Comment by YasinH** [comment]
Tested the last update, it seems like the UI is also vertically compressed? I remember when I resized the previous UI, the sections used to scale up and down with it, I loved it! Having those gaps between the sections vertically would be awesome!

**Comment by YasinH** [comment]
Another tiny fix would be to change "Run QC fixes" to "QC fixes", because the Run button is already in front of it.

**Comment by Kif11** [comment]
* Renamed QC fixes
* Renamed Frame Start and Frame Range

**Comment by YasinH** [comment]
Excellent! Looks great. 
Great idea on making labels turn green after they are executed! I'm wondering if we should add that to callback too so that if the scene changes, the greens default back to white.

**Comment by Kif11** [comment]
Oh yeah, I forgot that.

**Comment by YasinH** [comment]
Cool! 

What do you think of putting Delete all layers as part of QC fixes (at its beginning), and merging "create display layers" and "create groups" into a single "Create groups & display layers"? This would simplify the UI furhter and free up more space if we wanted to add more major functions to the UI

**Comment by Kif11** [comment]
QC fixes are logical separation of QC Tool scripts that I reference. Let's do it when we will need to add more functions.

**Comment by YasinH** [comment]
Makes sense, how about merging those other two (groups & layers)? I don't think they are major functions per se, are they?

**Comment by Kif11** [comment]
I actually have been thinking about it today.

**Comment by YasinH** [comment]
Could we have the labels be colored too when doing Run Selected?

**Comment by Kif11** [comment]
What do you mean?

**Comment by YasinH** [comment]
I mean this green/red label text change that you have made after running each function. I'm wondering if it is possible to have that take effect when doing Run Selected on multiple functions so that it colors all functions labels that it has gone through

**Comment by Kif11** [comment]
Oh, I forgot to do that.

**Comment by Kif11** [comment]
All right. This is fixed.

**Comment by YasinH** [comment]
Great! Also, if those colors can get default back to white on opening a new scene that would be great!

**Comment by Kif11** [comment]
It is already in place. It doesn't work for you?

**Comment by YasinH** [comment]
Not really, the colors stay the same

**Comment by Kif11** [comment]
NOTE: Add On New scene callback to update UI.

**Comment by Kif11** [comment]
Added kAfterNew scene update UI callback. I'm closing this issue. @YasinH If you need any UI related fixes please open a new issue with the specific problem name.
