### ISSUE TITLE
Update Assets messes with Resolution

### ISSUE THREAD

**Issue by YasinH** [Kif11/lanoria-assembly#31]
When running asset updates in scenes, it messes up with the Resolution parameter on some assets and causes the parameter to disappear. Not only that, it doesn't retain the original Resolution state when the asset was referenced. 

1. Reference an older release of hlwSconce and notice Resolution paramter exists
2. Run asset update function and now that Resolution disappears as well as the Resolution gets set to low even though it was previously set to high when the asset was imported.

This is critical to fix! Let's prioritize it.

P.S. noticed updating bedSprings from v1 to v3 hangs maya.

**Comment by Kif11** [comment]
This is now bug. This is expected behavior. It reference _lo file by default. I can change it if you need. I think this function was written originally to do assembly for animation.

Here is some screenshots to demonstrate.

![screen shot 2016-04-11 at 4 16 34 pm](https://cloud.githubusercontent.com/assets/8003487/14445344/27c42434-0001-11e6-8570-61ec3c28633a.png)
![screen shot 2016-04-11 at 4 16 12 pm](https://cloud.githubusercontent.com/assets/8003487/14445345/27d6398a-0001-11e6-8075-7618607e0fba.png)

**Comment by Kif11** [comment]
I added *lod* parameter to updateAllRefs function. Which is set to *hi* for anim2light. Test it and close this issue.

**Comment by YasinH** [comment]
Now we are talking! And it works as expected. 
Previously, it was indeed a bug from an end user point of view. When the animator ran it, he'd see everything changes in the scene and specially when that parameter disappears it questions the function.
It's good now, anyway. I'll pass it over so they can test it again.
